# Generated by Django 5.2.8 on 2025-11-15 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(max_length=100, verbose_name="연구실 이름"),
                ),
                (
                    "schedule_info",
                    models.TextField(blank=True, verbose_name="면담 가능 시간"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="랩 관리자 계정",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="공고 제목")),
                (
                    "description",
                    models.TextField(
                        help_text="모집 대상, 필요 역량, 기간 등 자세한 내용을 적어주세요.",
                        verbose_name="상세 내용",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to="job_postings/",
                        verbose_name="첨부파일 (PDF 등)",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="모집 마감일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lab.labprofile",
                        verbose_name="연구실",
                    ),
                ),
            ],
        ),
    ]
