# Generated by Django 5.2.8 on 2025-11-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labprofile",
            name="lab_instruction",
            field=models.CharField(blank=True, max_length=500, verbose_name="랩 소개"),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="lab_link",
            field=models.URLField(blank=True, verbose_name="랩실 링크"),
        ),
    ]
