# Generated by Django 5.2.8 on 2025-11-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_application"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="saved_labs",
            field=models.ManyToManyField(
                blank=True, related_name="scrapped_by_students", to="lab.labprofile"
            ),
        ),
    ]
