# Generated by Django 5.2.8 on 2025-11-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_labprofile_lab_instruction_labprofile_lab_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labprofile",
            name="schedule_info",
        ),
        migrations.CreateModel(
            name="LabAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "월요일"),
                            (2, "화요일"),
                            (3, "수요일"),
                            (4, "목요일"),
                            (5, "금요일"),
                            (6, "토요일"),
                            (7, "일요일"),
                        ],
                        verbose_name="요일",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="시작 시간")),
                ("end_time", models.TimeField(verbose_name="종료 시간")),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="lab.labprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "면담 가능 시간",
                "verbose_name_plural": "면담 가능 시간 목록",
                "ordering": ["day", "start_time"],
            },
        ),
    ]
