# Generated by Django 5.2.8 on 2025-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_remove_labprofile_schedule_info_labavailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="labprofile",
            name="professor_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="교수님 성함"
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="쉼표(,)로 구분하여 입력 (예: 인공지능,컴퓨터비전,HCI)",
                max_length=255,
                verbose_name="검색 태그",
            ),
        ),
    ]
