# Generated by Django 5.2.8 on 2025-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0004_labprofile_professor_name_labprofile_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="labprofile",
            name="github_projects_json",
            field=models.JSONField(
                blank=True, default=list, verbose_name="GitHub 프로젝트 캐시"
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="github_username",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="GitHub Username (또는 Organization)",
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="last_external_sync",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="최종 외부 연동 시간"
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="research_summary_ko",
            field=models.TextField(blank=True, verbose_name="AI 생성 연구 요약 (한글)"),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="scholar_author_id",
            field=models.CharField(
                blank=True,
                help_text="Google Scholar 프로필 URL의 'user=' 뒤에 있는 ID (예: AAAAAA-BBBB)",
                max_length=50,
                verbose_name="Google Scholar Author ID",
            ),
        ),
    ]
