# Generated by Django 5.2.8 on 2025-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0005_labprofile_github_projects_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labprofile",
            name="dbpia_papers_json",
            field=models.JSONField(
                blank=True, default=list, verbose_name="DBPia 논문 캐시"
            ),
        ),
    ]
