# Generated by Django 5.2.8 on 2025-11-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_labprofile_dbpia_papers_json"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_text",
                    models.TextField(verbose_name="지원 동기 및 자기소개"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "분석 대기중"),
                            ("RECOMMENDED", "추천"),
                            ("NOT_RECOMMENDED", "비추천"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("ai_summary", models.TextField(blank=True, verbose_name="AI 요약")),
                (
                    "ai_pros",
                    models.JSONField(
                        blank=True, default=list, verbose_name="AI 분석 장점"
                    ),
                ),
                (
                    "ai_cons",
                    models.JSONField(
                        blank=True, default=list, verbose_name="AI 분석 단점"
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="lab.jobposting",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="student.studentprofile",
                    ),
                ),
            ],
        ),
    ]
