# Generated by Django 5.2.8 on 2025-11-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_application"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labprofile",
            old_name="lab_instruction",
            new_name="lab_description",
        ),
    ]
